import type { Metadata } from "next";
import "../styles/globals.css";
import { NavbarDemo } from "@/components/NavBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NavbarDemo />
        <div>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
